variables:
  APPLICATION_NAME: ecom-api
  DOCKER_DRIVER: overlay2
  FF_USE_FASTZIP: 1
  FF_SCRIPT_SECTIONS: 1
  DOCKERFILE_LOCATION: 'Dockerfile'

stages:
  - test
  - build
  - deploy-dev

include:
  - project: 'innovate-tech/infrasturcture/templates'
    ref: main
    file: 'backend/build.yaml'
  - project: 'innovate-tech/infrasturcture/templates'
    ref: main
    file: 'backend/deploy-hsa.yaml'
  - project: 'innovate-tech/infrasturcture/templates'
    ref: main
    file: 'security/trivy-backend.yaml'
